apiVersion: v1
kind: Namespace
metadata:
  name: jenkins-namespace
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins-namespace
spec:
  selector:
    app: jenkins
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000  # Specify a nodePort in the range allowed by your cluster or leave it out for an automatic assignment
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  namespace: jenkins-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
